apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: mern-app
type: Opaque
# kubectl create secret generic mongodb-secret \
#   --from-literal=mongodb-uri="mongodb+srv://..." -n mern-app
data:
  mongodb-uri: BASE64_ENCODED_ATLAS_URI
